# Generated by Django 5.1.3 on 2024-12-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='image',
            new_name='url',
        ),
    ]
