# Generated by Django 5.1.3 on 2025-03-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_tenant_myhome_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myhome',
            old_name='user',
            new_name='tenant',
        ),
    ]
