# Generated by Django 5.1.3 on 2024-12-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_maintenancerequest_tenantapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
