# Generated by Django 5.1.3 on 2025-04-02 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_alter_propertyimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='url',
        ),
    ]
