# Generated by Django 5.1.3 on 2025-01-28 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'tenant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_as_tenant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(limit_choices_to={'role': 'landlord'}, on_delete=django.db.models.deletion.CASCADE, related_name='properties_as_landlord', to=settings.AUTH_USER_MODEL),
        ),
    ]
