name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Set up SSH for GitHub
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PA_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          PA_SSH_PRIVATE_KEY: ${{ secrets.PA_SSH_PRIVATE_KEY }}

      
      - name: Pull latest code from GitHub on PythonAnywhere
        run: |
          ssh -o StrictHostKeyChecking=no spbproperty@spbproperty.pythonanywhere.com "cd ~/Property-management-Backend && git pull"
        

      - name: Reload Web App on PythonAnywhere
        env:
          API_KEY: ${{ secrets.PYTHONANYWHERE_API_KEY }}
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/spbproperty/webapps/spbproperty.pythonanywhere.com/reload/" \
          -H "Authorization: Token $API_KEY"
