name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Update code on PythonAnywhere
        env:
          PA_USER: ${{ secrets.PYTHONANYWHERE_USER }}
          PA_PASS: ${{ secrets.PYTHONANYWHERE_PASSWORD }}
        run: |
          pip install fabric
          python -c "from fabric import Connection; c = Connection('$PA_USER.pythonanywhere.com', user='$PA_USER', connect_kwargs={'password': '$PA_PASS'}); c.run('cd ~/spbproperty && git pull')"

      - name: Reload PythonAnywhere Web App
        env:
          API_KEY: ${{ secrets.PYTHONANYWHERE_API_KEY }}
        run: |
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/spbproperty/webapps/spbproperty.pythonanywhere.com/reload/" \
          -H "Authorization: Token $API_KEY"